/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.yumemi.koma;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String hello(String name) {
        return "Hello %s!".formatted(name);
    }

    public String hi(String name) {
        return "Hi %s!".formatted(name);
    }
}
