/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.yumemi.koma;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String hello(String name) {
        return "Hello %s in %s!".formatted(name, version());
    }

    public String hi(String name) {
        return "Hi %s in %s!".formatted(name, version());
    }

    static String version() {
        return "1.3";
    }
}
