/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.yumemi.koma;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void helloMessage() {
        var lib = new Library();
        assertNotNull(lib);
    }
}
