/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.co.yumemi.koma;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void instance() {
        var lib = new Library();
        assertNotNull(lib);
    }

    @Test
    void helloMessage() {
        var lib = new Library();
        var message = lib.hello("me");
        assertEquals("Hello me in %s!".formatted(Library.version()), message);
    }

    @Test
    void hiMessage() {
        var lib = new Library();
        var message = lib.hi("me");
        assertEquals("Hi me in %s!".formatted(Library.version()), message);
    }
}
