name = "koma-maven-worker"
compatibility_date = "2023-01-01"
workers_dev = false

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MAVEN_BUCKET"
bucket_name = "koma-maven"
preview_bucket_name = "koma-maven"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
